# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [5]:
# your code here
np.version.version

'1.13.3'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [7]:
# Method 1
a = np.random.randint(10, size = (2,3,5))

array([[[0, 0, 6, 3, 8],
        [6, 1, 3, 6, 2],
        [9, 0, 0, 1, 3]],

       [[2, 0, 7, 6, 5],
        [5, 0, 4, 6, 5],
        [1, 3, 8, 4, 4]]])

In [8]:
# Method 2
a = np.random.rand(2,3,5)

array([[[ 0.3549291 ,  0.89812227,  0.89786584,  0.43010079,  0.13756697],
        [ 0.25256653,  0.92102923,  0.62178569,  0.00295169,  0.59147484],
        [ 0.68537587,  0.39190549,  0.92508984,  0.73890109,  0.28613511]],

       [[ 0.61371939,  0.52308946,  0.42633648,  0.63070103,  0.01471716],
        [ 0.0849422 ,  0.07012839,  0.01995443,  0.43662528,  0.20265591],
        [ 0.27239993,  0.98501037,  0.11382597,  0.95202461,  0.15717862]]])

In [10]:
# Method 3
a = np.random.random((2,3,5))

array([[[ 0.00453782,  0.47251152,  0.65513617,  0.89370211,  0.91464052],
        [ 0.35606786,  0.68149792,  0.37211451,  0.2493357 ,  0.66608051],
        [ 0.71459267,  0.68722356,  0.20916865,  0.98338451,  0.28154909]],

       [[ 0.83752622,  0.12378486,  0.77380373,  0.43270332,  0.26392168],
        [ 0.02528723,  0.5352501 ,  0.35521185,  0.05175587,  0.64898055],
        [ 0.52616383,  0.94453068,  0.17055731,  0.15094225,  0.63495276]]])

#### 4. Print *a*.


In [11]:
# your code here
print(a)

[[[ 0.00453782  0.47251152  0.65513617  0.89370211  0.91464052]
  [ 0.35606786  0.68149792  0.37211451  0.2493357   0.66608051]
  [ 0.71459267  0.68722356  0.20916865  0.98338451  0.28154909]]

 [[ 0.83752622  0.12378486  0.77380373  0.43270332  0.26392168]
  [ 0.02528723  0.5352501   0.35521185  0.05175587  0.64898055]
  [ 0.52616383  0.94453068  0.17055731  0.15094225  0.63495276]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [14]:
# your code here
print(b)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [15]:
# your code here
print(a.size == b.size)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [16]:
# your answer here
print(a.shape == b.shape)

False


They have the same size but not the same shape. If we try to add a and b we get an error

In [17]:
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [18]:
# your code here
c = np.transpose(b, [1, 2, 0])

In [20]:
print(a.shape, '-', c.shape)

(2, 3, 5) - (2, 3, 5)


It works because now the two arrays have the same shape

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [21]:
# your code/answer here
d=np.add(a, c)

It works because now the two arrays have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [22]:
# your code/answer here
print('A')
print(a)
print('D')
print(d)

A
[[[ 0.00453782  0.47251152  0.65513617  0.89370211  0.91464052]
  [ 0.35606786  0.68149792  0.37211451  0.2493357   0.66608051]
  [ 0.71459267  0.68722356  0.20916865  0.98338451  0.28154909]]

 [[ 0.83752622  0.12378486  0.77380373  0.43270332  0.26392168]
  [ 0.02528723  0.5352501   0.35521185  0.05175587  0.64898055]
  [ 0.52616383  0.94453068  0.17055731  0.15094225  0.63495276]]]
D
[[[ 1.00453782  1.47251152  1.65513617  1.89370211  1.91464052]
  [ 1.35606786  1.68149792  1.37211451  1.2493357   1.66608051]
  [ 1.71459267  1.68722356  1.20916865  1.98338451  1.28154909]]

 [[ 1.83752622  1.12378486  1.77380373  1.43270332  1.26392168]
  [ 1.02528723  1.5352501   1.35521185  1.05175587  1.64898055]
  [ 1.52616383  1.94453068  1.17055731  1.15094225  1.63495276]]]


The relation between terms in a and d is:

d[n][m][p] = a[n][m][p] + c[n][m][p]

when c[n][m][p] = 1, n = {0,1}, m = {0,1,2}, p = {0,1,2,3,4}.

We add one to every element in a.

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [23]:
# your code here
e = np.multiply(a,c)

#### 13. Does *e* equal to *a*? Why or why not?



Yes. The relation between terms in a and e is:

e[n][m][p] = a[n][m][p] * c[n][m][p]

when c[n][m][p] = 1, n = {0,1}, m = {0,1,2}, p = {0,1,2,3,4}.

We multiply by 1 every element in a, so the resulting array e should be equal to a.

In [24]:
print(a == e)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [25]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

In [26]:
print('MAX:  ', d_max)
print('MIN:  ', d_min)
print('MEAN: ', d_mean)

MAX:   1.98338450819
MIN:   1.0045378227
MEAN:  1.48723051155


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [27]:
# your code here
f = np.empty((2, 3, 5), dtype=np.int8)

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [28]:
# your code here
it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0;
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25
    elif it[0] == d_mean:
        f[it.multi_index] = 50;
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75
    else:
        f[it.multi_index] = 100
    it.iternext()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [29]:
# your code here
print('D')
print(d)
print('F')
print(f)

D
[[[ 1.00453782  1.47251152  1.65513617  1.89370211  1.91464052]
  [ 1.35606786  1.68149792  1.37211451  1.2493357   1.66608051]
  [ 1.71459267  1.68722356  1.20916865  1.98338451  1.28154909]]

 [[ 1.83752622  1.12378486  1.77380373  1.43270332  1.26392168]
  [ 1.02528723  1.5352501   1.35521185  1.05175587  1.64898055]
  [ 1.52616383  1.94453068  1.17055731  1.15094225  1.63495276]]]
F
[[[  0  25  75  75  75]
  [ 25  75  25  25  75]
  [ 75  75  25 100  25]]

 [[ 75  25  75  25  25]
  [ 25  75  25  25  75]
  [ 75  75  25  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [30]:
# your code here
g = np.empty((2, 3, 5), dtype=str)
it = np.nditer(d, flags=['multi_index'])
while not it.finished:
    if it[0] == d_min:
        g[it.multi_index] = 'A'
    elif it[0] > d_min and it[0] < d_mean:
        g[it.multi_index] = 'B'
    elif it[0] == d_mean:
        g[it.multi_index] = 'C'
    elif it[0] > d_mean and it[0] < d_max:
        g[it.multi_index] = 'D'
    else:
        g[it.multi_index] = 'E'
    it.iternext()

In [31]:
print('G')
print(g)

G
[[['A' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'D' 'B' 'E' 'B']]

 [['D' 'B' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['D' 'D' 'B' 'B' 'D']]]
